### ISSUE TITLE
Assertion failure in fq.cpp:107

### ISSUE THREAD

**Issue by hintjens** [zeromq/libzmq#1143]
Getting this when testing Zyre:

```
#0  0x00007f01f9d7f425 in __GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007f01f9d82b8b in __GI_abort () at abort.c:91
#2  0x00007f01f9b00a09 in zmq::zmq_abort (errmsg_=<optimized out>) at err.cpp:74
#3  0x00007f01f9b00cff in zmq::fq_t::recvpipe (this=0x7f01ec00b050, msg_=0x7f01ec009194, pipe_=0x7f01f6a49cb8) at fq.cpp:107
#4  0x00007f01f9b2c7cd in zmq::router_t::xrecv (this=0x7f01ec00ab60, msg_=0x7f01ec009194) at router.cpp:314
#5  0x00007f01f9b183aa in zmq::socket_base_t::recv (this=0x7f01ec00ab60, msg_=0x7f01ec009194, flags_=0) at socket_base.cpp:870
#6  0x00007f01f9b31999 in s_recvmsg (s_=<optimized out>, msg_=0x7f01ec009194, flags_=<optimized out>) at zmq.cpp:446
#7  0x00007f01fa343bb6 in zframe_recv (source=<optimized out>) at zframe.c:108
#8  0x00007f01fa34b696 in zmsg_recv (source=<optimized out>) at zmsg.c:111
#9  0x00007f01fa10f484 in zre_msg_recv (input=0x7f01ec012230) at zre_msg.c:633
#10 0x00007f01fa113acd in zyre_node_recv_peer (self=0x7f01ec00aad0) at zyre_node.c:572
#11 zyre_node_actor (pipe=<optimized out>, args=<optimized out>) at zyre_node.c:816
#12 0x00007f01fa339253 in s_thread_shim (args=0x7f01e8007e90) at zactor.c:64
#13 0x00007f01f96c7e9a in start_thread (arg=0x7f01f6a4a700) at pthread_create.c:308
#14 0x00007f01f9e3d3fd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
```

Test case is zyre/tools/ztester_gossip, with this syntax:

```
ztester_gossip 2 100
```

(2 nodes, 100 iterations).

fq.cpp assert hits most times after a few iterations. Note that this needs latest CZMQ and Zyre masters.

**Comment by bluca** [comment]
Closing as this was fixed by https://github.com/zeromq/libzmq/pull/1645
