### ISSUE TITLE
Client hangs on recv

### ISSUE THREAD

**Issue by mohitanchlia** [zeromq/libzmq#1194]
I am trying to use router/dealer with dealer using inproc://, when I run my program the router seems to bind to the port (netstat), client seem to connect successfully but the recv after send hangs. Worker on the other hand doesn't see the request come in from router/dealer. Here is the snippet of my code, not sure what is wrong here:

Router/Dealer:

  log.info("Starting ZeroMQ Router on port=" + port);
        //  Prepare our context and socket
        ZMQ.Context context = ZMQ.context(1);
        // Socket to talk to clients
        ZMQ.Socket clients = context.socket(ZMQ.ROUTER);
        clients.bind("tcp://*:" + port);

```
    // Socket to talk to workers
    ZMQ.Socket workers = context.socket(ZMQ.DEALER);
    workers.bind("inproc://workers");

    // Connect work threads to client threads via a queue
    ZMQQueue queue = new ZMQQueue(context, clients, workers);
    new Thread(queue).start();

    log.info("Exiting ZeroMQ");
```

Worker:

 public JMSZMQRepServer() {
  this.context = ZMQ.context(1);
  socket = context.socket(ZMQ.REP);
  socket.connect("inproc://workers");
  log.info("Server bind inproc");
 }

 @Override
 public void run() {

  while (true) {

   // Wait for next request from client (C string)

   try {
    log.info("Start");

```
String request = socket.recvStr(0);

// String request = new String(GZIPUtils.gunzip(socket.recv()));
// Do some 'work'
String response = null;
response = doWork(request);

// Send reply back to client (C string)
socket.send(response, 0);
```

   } catch (ZMQException e) {
    if (e.getErrorCode() == ZMQ.Error.ETERM.getCode()) {
     log.warn("Exiting ", e.getMessage());
     break;
    } else {
     log.error("Unable to send request", e);
    }
   } catch (Exception e) {
    // TODO Auto-generated catch block
    log.error("Error in gunzip", e);
   }
  }
  if (null != socket) {
   log.info("Socket closed");
   socket.close();
  }

 }

Client:

 public JMSZMQClient() {
  context = ZMQ.context(1);
  requester = context.socket(ZMQ.REQ);

  requester.connect("inproc://workers");
  log.info("Connected to in proc workers");
 }

 public String processRequest(String json) throws DataStoreException {
  String result = null;
  long latency = System.currentTimeMillis();
  // byte [] bJson = GZIPUtils.gzip(json.getBytes());
  log.info("Send request to zMQ server");

  // requester.send(bJson);
  requester.send(json, 0);
  result = requester.recvStr(0);
  log.info("ZeroMQ  client took="
    + (System.currentTimeMillis() - latency));

  MessageUtil.validateZMQMessage(result);

  return result;
 }
--------------------- Stack trace

"pool-2-thread-10" prio=10 tid=0x00007f9ea91cd800 nid=0xf87 runnable [0x00007f9e750ab000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000000897f9ce8> (a sun.nio.ch.Util$2)
        - locked <0x00000000897f9cd8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000897f9bc0> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at zmq.Signaler.wait_event(Signaler.java:135)
        at zmq.Mailbox.recv(Mailbox.java:105)
        at zmq.SocketBase.process_commands(SocketBase.java:793)
        at zmq.SocketBase.recv(SocketBase.java:714)
        at org.zeromq.ZMQ$Socket.recv(ZMQ.java:1247)
        at org.zeromq.ZMQ$Socket.recvStr(ZMQ.java:1318)

"iothread-2" prio=10 tid=0x00007f9e8c080800 nid=0xf85 runnable [0x00007f9e7512d000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000000890bafc0> (a sun.nio.ch.Util$2)
        - locked <0x00000000890bafb0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000890bae98> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at zmq.Poller.run(Poller.java:207)
        at java.lang.Thread.run(Thread.java:745)

"reaper-1" prio=10 tid=0x00007f9e8c04c000 nid=0xf84 runnable [0x00007f9e7516e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000000890aa0e0> (a sun.nio.ch.Util$2)
        - locked <0x00000000890aa0d0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000890a9fb8> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at zmq.Poller.run(Poller.java:207)
        at java.lang.Thread.run(Thread.java:745)

**Comment by sigiesec** [comment]
I think you are using JeroMQ. So this should be raised in zeromq/jeromq instead.
