### ISSUE TITLE
errno_assert failed in epoll_t::rm_fd() at epoll.cpp:81

### ISSUE THREAD

**Issue by jinq0123** [zeromq/libzmq#1249]
Zeromq-3.2.2
In rare case.

```
Core was generated by `/home/ztgame/S20141023R2/server_bin/gameserver/lx_gameserver start --daemon --i'.
Program terminated with signal 6, Aborted.
#0  0x000000323e832a45 in raise () from /home/ztgame/thserver_so/libc.so.6

Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.25.el6.x86_64
(gdb) bt
#0  0x000000323e832a45 in raise () from /home/ztgame/thserver_so/libc.so.6
#1  0x000000323e834225 in abort () from /home/ztgame/thserver_so/libc.so.6
#2  0x00007f9f227122b9 in zmq::zmq_abort (

errmsg_=0x591d <Address 0x591d out of bounds>) at err.cpp:76
#3  0x00007f9f22712108 in zmq::epoll_t::rm_fd (this=0x2f26030,

handle_=<value optimized out>) at epoll.cpp:81
#4  0x00007f9f2271cfb8 in zmq::reaper_t::process_stop (this=0x2f25f50)

at reaper.cpp:93
#5  0x00007f9f2271d104 in zmq::reaper_t::in_event (this=0x2f25f50)

at reaper.cpp:72
#6  0x00007f9f22711b82 in zmq::epoll_t::loop (this=0x2f26030) at epoll.cpp:162
#7  0x00007f9f2272999b in thread_routine (arg_=0x2f260a0) at thread.cpp:83
#8  0x000000323ec077e1 in start_thread ()

   from /home/ztgame/thserver_so/libpthread.so.0
#9  0x000000323e8e68ed in clone () from /home/ztgame/thserver_so/libc.so.6

(gdb) 
```

```
void zmq::epoll_t::rm_fd (handle_t handle_)
{
        ...
80:   int rc = epoll_crt (epoll_fd, EPOLL_CTL_DEL, pe->fd, &pe->ev);
81:   errno_assert (rc != -1);
        ...
}
````

**Comment by sigiesec** [comment]
Closing this issue, since ZeroMQ 3.x is no longer supported. Maybe you can try the most recent 3.x version (3.2.5) or update to a current 4.x version.
