### ISSUE TITLE
Assertion failed at src/signaler.cpp:293

### ISSUE THREAD

**Issue by wcs1only** [zeromq/libzmq#1634]
Zeromq version 4.1.3

    #0  0x00007fb3d9aae625 in raise () from /lib64/libc.so.6
    #1  0x00007fb3d9aafe05 in abort () from /lib64/libc.so.6
    #2  0x00007fb3dbb0e289 in zmq::zmq_abort (errmsg_=0xa719 <Address 0xa719 out of bounds>) at src/err.cpp:84
    #3  0x00007fb3dbb27030 in zmq::signaler_t::recv (this=0x18a2d120) at src/signaler.cpp:293
    #4  0x00007fb3dbb12658 in zmq::mailbox_t::recv (this=0x18a2d0c0, cmd_=0x7fb3d44386a0, timeout_=<value optimized out>) at src/mailbox.cpp:87
    #5  0x00007fb3dbb27b44 in zmq::socket_base_t::process_commands (this=0x18a2cd00, timeout_=<value optimized out>, throttle_=false) at src/socket_base.cpp:984
    #6  0x00007fb3dbb27e06 in zmq::socket_base_t::recv (this=0x18a2cd00, msg_=0x7fb3d4438a60, flags_=<value optimized out>) at src/socket_base.cpp:916
    #7  0x00007fb3dbb3d1c9 in s_recvmsg (s_=<value optimized out>, msg_=0x7fb3d4438a60, flags_=<value optimized out>) at src/zmq.cpp:456
    #8  0x00000000007d7866 in ZmqClient::recvFrame (this=0x13cb5b180, msg=<value optimized out>) at /usr/local/projects/libhwscdn/src/lib/zeromq/zmqclient.C:100
    #9  0x00000000007d7da4 in ZmqClient::sendMessage (this=0x13cb5b180, eProtocol=<value optimized out>, vMessages=..., vReply=...) at /usr/local/projects/libhwscdn/src/lib/zeromq/zmqclient.C:73
    #10 0x00000000007d8d46 in ZmqClient::sendMessage (this=0x13cb5b180, eProtocol=ZmqProtocols::eCCM, sMessage=<value optimized out>, vReply=...) at /usr/local/projects/libhwscdn/src/lib/zeromq/zmqclient.C:38

I received 5 failed assertions identical to this one in our production environment last night. It appears to be a race or triggered by some unique event, since not all of our hosts were affected. A closer examination of the assert in question:

    void zmq::signaler_t::recv ()
    {
        //  Attempt to read a signal.
        #if defined ZMQ_HAVE_EVENTFD
        uint64_t dummy;
        ssize_t sz = read (r, &dummy, sizeof (dummy));
        errno_assert (sz == sizeof (dummy));

        //  If we accidentally grabbed the next signal along with the current
        //  one, return it back to the eventfd object.
        if (unlikely (dummy == 2)) {
            const uint64_t inc = 1;
            ssize_t sz2 = write (w, &inc, sizeof (inc));
            errno_assert (sz2 == sizeof (inc));
            return;
        }

        zmq_assert (dummy == 1);

In all 5 cases, dummy appeared to be an uninitialized 64-bit int. 

    (gdb) print/x dummy
    $2 = 0xc1d47a1a00030316

    (gdb) print/x dummy 
    $2 = 0x515e2d1a00030315

    (gdb) print/x dummy
    $2 = 0xf951ac1a00030316

    (gdb) print/x dummy
    $2 = 0xfd3e6bebd83ccae3

    (gdb) print/x dummy
    $5 = 0xb8a7845c9e80c457

We get passed the sz==sizeof(dummy) check, so I assume that means the read was valid, and somebody previously wrote garbage to the FD. That seems to be the extent of what I have been able to diagnose.

**Comment by wcs1only** [comment]
The more I look in to this, I think this a corruption in our application code. Possible a use after close on one of our application FDs. If I can confirm that, I'll close this ticket.

**Comment by wcs1only** [comment]
Yeah, a detailed investigation revealed a write after close FD bug in our application. If zeromq happened to pick up that FD for the signaler FD, our application could be responsible for the garbage read off the socket. I'm closing this. If it comes back after we fix our code, I'll reopen this ticket.
