### ISSUE TITLE
test_router_mandatory_hwm failing on windows

### ISSUE THREAD

**Issue by diorcety** [zeromq/libzmq#2017]
Hi,
I have noticed a strange issue on windows in the test_router_mandatory_hwm test.

FAIL tests/test_router_mandatory_hwm.exe (exit status: 21)

After some investigating, closing the client socket will break the server socket (the one provided by accept()) with getsockopt in zmq::select_t::get_fd_family

Here the gdb session

```


(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/diorcet/libzmq/tests/.libs/test_router_mandatory_hwm.exe
[New Thread 2024.0x18ec]

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb) c
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 1, 0x000007feff0318e9 in closesocket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 1, 0x000007feff0318e9 in closesocket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.
[New Thread 2024.0x17a8]

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 1, 0x000007feff0318e9 in closesocket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.
[New Thread 2024.0x5dc]

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 1, 0x000007feff0318e9 in closesocket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=<optimized out>, type_=type_@entry=1, protocol_=protocol_@entry=6) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 10, zmq::open_socket (domain_=domain_@entry=2, type_=type_@entry=1, protocol_=protocol_@entry=0) at src/ip.cpp:79
79      }
(gdb)
Continuing.

Breakpoint 1, 0x000007feff0318e9 in closesocket () from /c/Windows/system32/WS2_32.dll
(gdb)
Continuing.

Breakpoint 14, main () at tests/test_router_mandatory_hwm.cpp:72
72          rc = zmq_connect (dealer, "tcp://127.0.0.1:5560");
(gdb)
Continuing.
[Switching to Thread 2024.0x5dc]

Breakpoint 9, 0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
(gdb) bt
#0  0x000007feff03de9f in socket () from /c/Windows/system32/WS2_32.dll
#1  0x000000006b34f65f in zmq::open_socket (domain_=<optimized out>, type_=type_@entry=1, protocol_=protocol_@entry=6) at src/ip.cpp:55
#2  0x000000006b376660 in zmq::tcp_connecter_t::open (this=this@entry=0x1cc2b90) at src/tcp_connecter.cpp:268
#3  0x000000006b376d6e in zmq::tcp_connecter_t::start_connecting (this=0x1cc2b90) at src/tcp_connecter.cpp:186
#4  0x000000006b355f09 in zmq::object_t::process_command (this=0x1cc2b90, cmd_=...) at src/object.cpp:90
#5  0x000000006b34f5cb in zmq::io_thread_t::in_event (this=0x1cb27c0) at src/io_thread.cpp:85
#6  0x000000006b3637bc in zmq::select_t::loop (this=0x1cb24b0) at src/select.cpp:318
#7  0x000000006b377c0d in thread_routine (arg_=<optimized out>) at src/thread.cpp:46
#8  0x000007fefde9415f in srand () from /c/Windows/system32/msvcrt.dll
#9  0x000007fefde96ebd in msvcrt!_ftime64_s () from /c/Windows/system32/msvcrt.dll
#10 0x00000000778759bd in KERNEL32!BaseThreadInitThunk () from /c/Windows/system32/kernel32.dll
#11 0x0000000077aaa2e1 in ntdll!RtlUserThreadStart () from /c/Windows/SYSTEM32/ntdll.dll
#12 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) c
Continuing.

Breakpoint 10, zmq::open_socket (domain_=<optimized out>, type_=type_@entry=1, protocol_=protocol_@entry=6) at src/ip.cpp:79
79      }
(gdb) p s
$59 = 208
(gdb) c
Continuing.
[New Thread 2024.0x1bb4]

Breakpoint 2, zmq::tcp_listener_t::accept (this=this@entry=0x33fb70) at src/tcp_listener.cpp:334
334     }
(gdb) p socket
$60 = (zmq::socket_base_t *) 0x33edb0
(gdb) p sock
$61 = 236
(gdb) p s
$62 = 204
(gdb) c
Continuing.
[Switching to Thread 2024.0x18ec]

Breakpoint 12, main () at tests/test_router_mandatory_hwm.cpp:115
115         rc = zmq_close (router);
(gdb) c
Continuing.

Breakpoint 13, main () at tests/test_router_mandatory_hwm.cpp:118
118         rc = zmq_close (dealer);
(gdb) c
Continuing.
[Switching to Thread 2024.0x5dc]

Breakpoint 6, zmq::tcp_listener_t::close (this=this@entry=0x33fb70) at src/tcp_listener.cpp:129
129         int rc = closesocket (s);
(gdb) p s
$63 = 204
(gdb) call zmq::select_t::get_fd_family(236)
$64 = 2
(gdb) c
Continuing.

Breakpoint 1, 0x000007feff0318e9 in closesocket () from /c/Windows/system32/WS2_32.dll
(gdb) c
Continuing.

Breakpoint 7, zmq::stream_engine_t::~stream_engine_t (this=0x1cc3c70, __in_chrg=<optimized out>) at src/stream_engine.cpp:150
150             int rc = closesocket (s);
(gdb) call zmq::select_t::get_fd_family(236)
$65 = 2
(gdb) p s
$66 = 208
(gdb) c
Continuing.

Breakpoint 1, 0x000007feff0318e9 in closesocket () from /c/Windows/system32/WS2_32.dll
(gdb) c
Continuing.

Breakpoint 5, zmq::stream_engine_t::~stream_engine_t (this=0x1cc3c70, __in_chrg=<optimized out>) at src/stream_engine.cpp:151
151             wsa_assert (rc != SOCKET_ERROR);
(gdb) call zmq::select_t::get_fd_family(236)

Breakpoint 3, zmq::select_t::get_fd_family (fd_=236) at src/select.cpp:457
457         return AF_UNSPEC;
The program being debugged stopped while in a function called from GDB.
Evaluation of the expression containing the function
(zmq::select_t::get_fd_family(unsigned long long)) will be abandoned.
When the function is done executing, GDB will silently stop.
(gdb)

```

**Comment by sigiesec** [comment]
I believe this was fixed by #2731 
Please reopen if you can still see this failure with the current master
