### ISSUE TITLE
Failed to build in emscripten environment.

### ISSUE THREAD

**Issue by kavikumarN** [zeromq/libzmq#3437]
I am trying to build zeromq inside Emscripten environment, using official emscripten site guide. But Still i get error on building. Even if i built successfully, i get error for undefined symbols pthread,grggid, etc

**Comment by sigiesec** [comment]
I moved this to the libzmq repository, as you are apparently referring to that (cppzmq doesn't have an autotools build, besides it is not necessary to build anything since it is a header-only library). 

Without the files you refer to (ZMQHWSERVER.cpp, ZMQHWCLIENT.cpp, server.html, client.html), it is not possible to reprodruce your specific issue. However, I suspect that this won't work out of the box, and I am not sure if this can work at all, since libzmq contains a large portion of OS-specific code, and I don't know if this can be meaningfully run in a JavaScript environment. The tests should be run (what is normally done by make test, but I don't know if this would work directly this way). 

Depending on your use case, you might also give https://github.com/zeromq/zeromq.js/ a look, which provides JavaScript/node.js bindings to a native libzmq library.

**Comment by sigiesec** [comment]
I was actually able to reproduce this with a test:
```
✘-1 ~/libzmq-emscripten [master|…5] 
17:37 $ emmake make tests/test_pair_inproc
  CXX      tests/tests_test_pair_inproc-test_pair_inproc.o
  CXXLD    tests/test_pair_inproc
emcc:WARNING: ignoring dynamic library libzmq.so.5.2.2 because not compiling to JS or HTML, remember to link it when compiling to JS or HTML at the end
✔ ~/libzmq-emscripten [master|…5] 
17:38 $ emcc tests/tests_test_pair_inproc-test_pair_inproc.o src/.libs/libzmq.so external/unity/libunity.a -o test_pair.html
error: undefined symbol: eventfd
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: getgrgid
error: undefined symbol: pthread_getschedparam
error: undefined symbol: pthread_setaffinity_np
error: undefined symbol: pthread_setschedparam
Error: Aborting compilation due to previous errors
shared:ERROR: '/home/osboxes/emsdk/node/8.9.1_64bit/bin/node /home/osboxes/emsdk/emscripten/1.38.28/src/compiler.js /tmp/tmp9enwII.txt /home/osboxes/emsdk/emscripten/1.38.28/src/library_pthread_stub.js' failed (1)
```
If these are the only missing (and unsupported) symbols, this should be not too hard too fix. Apparently the configure gets some features wrong, or during build some wrong decutions are made, but all of these symbols are optional.

**Comment by sigiesec** [comment]
I just saw that there already is an emscripten issue about this (also referring to libzmq): emscripten-core/emscripten#5726

**Comment by sigiesec** [comment]
Ah, I failed to enable pthread support, so now I am down to:
```
17:51 $ emcc tests/tests_test_pair_inproc-test_pair_inproc.o src/.libs/libzmq.so external/unity/libunity.a  -s USE_PTHREADS=1 -o test_pair.html
error: undefined symbol: eventfd
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
error: undefined symbol: getgrgid
error: undefined symbol: pthread_setaffinity_np
Error: Aborting compilation due to previous errors
shared:ERROR: '/home/osboxes/emsdk/node/8.9.1_64bit/bin/node /home/osboxes/emsdk/emscripten/1.38.28/src/compiler.js /tmp/tmp5FAU3r.txt /home/osboxes/emsdk/emscripten/1.38.28/src/library_pthread.js' failed (1)
```

**Comment by sigiesec** [comment]
I now manually edited the generated src/platform.hpp and unset both ZMQ_HAVE_EVENTFD, ZMQ_HAVE_PTHREAD_SET_AFFINITY and ZMQ_HAVE_SO_PEERCRED, and rerun `emmake make clean ; emmake make`, and with that I get:
```
... pending ...
```

**Comment by sigiesec** [comment]
I installed chromium 71, and enabled WebAssembly threads support as described under https://developers.google.com/web/updates/2018/10/wasm-threads, but now I get the following error output:
```
Preallocating 2 workers for a pthread spawn pool.
unsupported socketcall syscall 8
abort("unsupported socketcall syscall 8") at Error
    at jsStackTrace (http://localhost:6931/test_pair.js:1053:13)
    at stackTrace (http://localhost:6931/test_pair.js:1070:12)
    at abort (http://localhost:6931/test_pair.js:9321:44)
    at ___syscall102 (http://localhost:6931/test_pair.js:6280:18)
    at wasm-function[1802]:212
    at wasm-function[1059]:95
    at wasm-function[1289]:18
    at wasm-function[1468]:77
    at wasm-function[1480]:265
    at wasm-function[1611]:46
```

**Comment by kavikumarN** [comment]
Hi. Thanks for your response. I have tried to build libzmq static library with following commands and tried to compile [ simple client and server programs.](https://github.com/booksbyus/zguide/tree/master/examples/C%2B%2B)

Even if i try to use zeromq.js nodejs bindings it works in terminal  perhaps in browsers it fails to run.I have tried to enable sharedarraybuffer in about:config of firefox.   
the steps i followed and errors i got:

` emcc  -c -s WASM=1 -O3 -s EXPORTED_FUNCTIONS="['_main','_zmq_socket','_zmq_bind','_zmq_send','_zmq_recv','_zmq_connect','_zmq_ctx_new','_zmq_ctx_destroy']" -s NO_EXIT_RUNTIME=1 -I/home/mat/emsdk/emscripten/incoming/system/include -s USE_PTHREADS=1 -lrt hwserver.c -o serfile.o`

`mat@ctpldc01:~/emsdk/emscripten/incoming/1319$ emcc -s WASM=1 -O3 -s NO_EXIT_RUNTIME=1 -s EXPORT_ALL=1 -s RUNTIME_LINKED_LIBS=-lrt -s USE_PTHREADS=1  ../system/lib/libzmq.a -o libfile.o`

`mat@ctpldc01:~/emsdk/emscripten/incoming/1319$ emcc -s WASM=1 -O3 -o finalserver.js serfile.o libfile.o -s USE_PTHREADS=1 -s PTHREAD_POOL_SIZE=2  -s RUNTIME_LINKED_LIBS=-lrt -s NO_EXIT_RUNTIME=1 -s EXPORT_ALL=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0`

When i tried to modify values in ZMQ_HAVE_EVENTFD, ZMQ_HAVE_PTHREAD_SET_AFFINITY and ZMQ_HAVE_SO_PEERCRED, still unable to clear these warnings.

`warning: undefined symbol: eventfd
warning: undefined symbol: getgrgid
warning: undefined symbol: pthread_setaffinity_np`

**Comment by sigiesec** [comment]
Did you try setting the ZMQ_* defines to 0? That doesn't work, and that's a bit confusing. You must remove the definitions completely.

**Comment by sigiesec** [comment]
I just learned that currently the sockets provided are a WebSocket emulation. Besides that you would need to use Websockify on the peer side (if that uses native ZMTP), this emulation doesn't support setsockopt at all, e.g., so this would definitely require adaptations in the code.

Maybe emscripten-core/emscripten#7672 will solve this, but it is still in review.

**Comment by bluca** [comment]
That's because they are ifdefs, the preprocessor does not check the value

**Comment by cowlicks** [comment]
@sigiesec the PR your'r referring to emscripten-core/emscripten#7672 has been merged and release. I was looking into running my zeromqjs code in the browser, and came across this, so I'm excited to see your results.

**Comment by space55** [comment]
Hi,

I just wanted to tune in. I'm looking into using ZeroMQ between a WASM client and a WebSocket server for pub/sub data distribution. Specifically, I'm using the Golang client, but this appears to be a libzmq error.

Is there any way I can build for WASM locally on my machine, now that emscripten-core/emscripten#7672 is completed?

Thanks!
