### ISSUE TITLE
zmq_msg_data fails and results SIGABRT while zmq_recv succeeded

### ISSUE THREAD

**Issue by HomuncDev0013** [zeromq/libzmq#3466]
# Issue description

I am developing a zmq subscriber using c/c++, the zmq publisher is developed with JavaScript.
With a message of less than 30 Bytes, I receive the message successfully using zmq_recv and zmq_msg_data functions, but for messages of size more than 30 Bytes, the function zmq_recv return successfully the size of the message, however the function zmq_msg_data fails and results a SIGABRT

# Environment

* libzmq version (commit hash if unreleased): 4.2.0
* OS: Ubuntu 16.04 64bits

# Minimal test code

```
#include <iostream>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <string.h>
#include "zmq.h"

#define CONNECTION_URL    (char *)"tcp://%s:%d"
#define max_prefix_size      64
#define max_data_size        10000

int main()
{ 
      void * m_AudioToCamZMQcontext =  (void *)zmq_ctx_new ();
      void * m_zmqClient = zmq_socket (m_AudioToCamZMQcontext, ZMQ_SUB);
      int size = sizeof(char)*(sizeof(CONNECTION_URL)+24);
      char * strCNX = (char *)malloc(size);
      snprintf(strCNX,size-1,CONNECTION_URL, IP, Port); // IP and Port are set by me
      int ret = zmq_connect (m_zmqClient, strCNX);
      ret = zmq_setsockopt (m_zmqClient, ZMQ_SUBSCRIBE,prefix,length); // prefix and length set by me

      zmq_msg_t zmq_prefix;
      int rc1 = zmq_msg_init (&zmq_prefix);
      rc1 = zmq_recv (m_zmqClient, &zmq_prefix, max_prefix_size, 0);
      char * prefix_content = zmq_msg_data(&zmq_prefix);

      zmq_msg_t zmq_data;
      int rc2 = zmq_msg_init (&zmq_data);
      rc2 = zmq_recv (m_zmqClient, &zmq_data, max_data_size, 0);
      char * data_content = zmq_msg_data(&zmq_data);

      return 0;
}
```

# What's the actual result? 
In the second reception of data:
```
Assertion failed: check () (msg.cpp:191)

Thread 1 received signal SIGABRT, Aborted.

#3  0x080583f8 in zmq::zmq_abort (errmsg_=errmsg_@entry=0x807ab40 "check ()") at err.cpp:76
#4  0x08059501 in zmq::msg_t::data (this=0xf7bf62fc) at msg.cpp:191

```

# What's the expected result?
Successful message reception

**Comment by bluca** [comment]
Please read the documentation of zmq_recv - it takes a buffer as a parameter, not a message:

http://api.zeromq.org/4-2:zmq-recv

**Comment by HomuncDev0013** [comment]
@bluca , thank you. I have mistaken reading the zmq_recv's documentation of a previous version.
