### ISSUE TITLE
zmq_poll crashes in xread_activated when using XPUB socket 

### ISSUE THREAD

**Issue by mrseanmorris** [zeromq/libzmq#3940]
# Issue description
Crash when `XPUB` socket receives multiple consecutive newlines.  This seems to happen the second time that `xread_activated` is called. 

# Environment
Linux

* libzmq version (commit hash if unreleased): 
4.3.1

* OS: 
Red Hat Enterprise Linux Server release 7.8 (Maipo)

# Minimal test code / Steps to reproduce the issue

1.  
```cpp
#include <zmq.h>
int main( int argc, char * argv[] )
{
    void *ctx = zmq_ctx_new();
    void *sock = zmq_socket( ctx, ZMQ_XPUB );
    zmq_bind(sock, "tcp://*:32001");
    while(1)
    {
        zmq_pollitem_t items[] = {
            { sock, 0, ZMQ_POLLIN, 0 }
        };
        zmq_poll( items, 1, 100 );
    }
}
```

2. connect to port 32001 with netcat and send around 22 newlines.  the code above will crash.  we initially encountered this problem when doing some port scans on hosts running zeroMQ code, so i'm sure it's not just based on newlines, but this is an easy way to get it to crash.

# What's the actual result? (include assertion message & call stack if applicable)
 % ./bin/zmq_test_publisher
Segmentation fault (core dumped)

stack :
```
#0  0x000000000045b6fb in zmq::xpub_t::xread_activated (this=0x741b80, pipe_=0x7fffec009570) at src/xpub.cpp:170
#1  0x000000000044c650 in zmq::socket_base_t::read_activated (this=0x741b80, pipe_=0x7fffec009570) at src/socket_base.cpp:1533
#2  0x00000000004418c6 in zmq::pipe_t::process_activate_read (this=0x7fffec009570) at src/pipe.cpp:276
#3  0x0000000000439e42 in zmq::object_t::process_command (this=0x7fffec009570, cmd_=...) at src/object.cpp:75
#4  0x000000000044beb7 in zmq::socket_base_t::process_commands (this=0x741b80, timeout_=0, throttle_=false) at src/socket_base.cpp:1358
#5  0x0000000000448756 in zmq::socket_base_t::getsockopt (this=0x741b80, option_=15, optval_=0x7fffffffd89c, optvallen_=0x7fffffffd8a0) at src/socket_base.cpp:450
#6  0x000000000042009a in zmq_getsockopt (s_=0x741b80, option_=15, optval_=0x7fffffffd89c, optvallen_=0x7fffffffd8a0) at src/zmq.cpp:267
#7  0x0000000000421719 in zmq_poll (items_=0x7fffffffda00, nitems_=1, timeout_=100) at src/zmq.cpp:943
#8  0x000000000041f7d9 in zmq::poll (items_=0x7fffffffda00, nitems_=1, timeout_=100) at include/zmq.hpp:156
#9  0x000000000041f5f3 in main (argc=1, argv=0x7fffffffdb38) at src/test_publisher.cpp:14
```

here are the local variables before line 165 is executed :

```
165     in src/xpub.cpp
(gdb) info locals
notify = true
msg_data = 0x7fffffffd578 "\n\n\n\n\n\n\n\n\n"
data = 0x0
metadata = 0x0
size = 0
subscribe = false
sub = {_u = {base = {metadata = 0x0, unused = "\n\n\n\n\n\n\n\n\n", '\000' <repeats 24 times>, "\t", type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, vsm = {metadata = 0x0,
      data = "\n\n\n\n\n\n\n\n\n", '\000' <repeats 23 times>, size = 9 '\t', type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, lmsg = {metadata = 0x0, content = 0xa0a0a0a0a0a0a0a,
      unused = "\n", '\000' <repeats 24 times>, "\t", type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, zclmsg = {metadata = 0x0, content = 0xa0a0a0a0a0a0a0a,
      unused = "\n", '\000' <repeats 24 times>, "\t", type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, cmsg = {metadata = 0x0, data = 0xa0a0a0a0a0a0a0a, size = 10,
      unused = '\000' <repeats 17 times>, "\t", type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, delimiter = {metadata = 0x0, unused = "\n\n\n\n\n\n\n\n\n", '\000' <repeats 24 times>, "\t",
      type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}}}


```
and after the crash :

```
(gdb) info locals
notify = true
msg_data = 0x7fffffffd578 "\n\n\n\n\n\n\n\n\n"
data = 0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>
metadata = 0x0
size = 1
subscribe = false
sub = {_u = {base = {metadata = 0x0, unused = "\n\n\n\n\n\n\n\n\n", '\000' <repeats 24 times>, "\t", type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, vsm = {metadata = 0x0,
      data = "\n\n\n\n\n\n\n\n\n", '\000' <repeats 23 times>, size = 9 '\t', type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, lmsg = {metadata = 0x0, content = 0xa0a0a0a0a0a0a0a,
      unused = "\n", '\000' <repeats 24 times>, "\t", type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, zclmsg = {metadata = 0x0, content = 0xa0a0a0a0a0a0a0a,
      unused = "\n", '\000' <repeats 24 times>, "\t", type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, cmsg = {metadata = 0x0, data = 0xa0a0a0a0a0a0a0a, size = 10,
      unused = '\000' <repeats 17 times>, "\t", type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}, delimiter = {metadata = 0x0, unused = "\n\n\n\n\n\n\n\n\n", '\000' <repeats 24 times>, "\t",
      type = 101 'e', flags = 0 '\000', group = '\000' <repeats 15 times>, routing_id = 0}}}

```

The code on line `xpub.cpp:170` is trying to dereference the data pointer and assign a value to it.  I see some suspicious comments next to identical code further up in the method :

```cpp
            //  ZMTP 3.1 hack: we need to support sub/cancel commands, but
            //  we can't give them back to userspace as it would be an API
            //  breakage since the payload of the message is completely
            //  different. Manually craft an old-style message instead.
```

# What's the expected result?

The API should not crash on input data regardless of whether it's formatted correctly.

**Comment by bluca** [comment]
Have you tried with latest master? The problem is not reproducible from there

**Comment by mrseanmorris** [comment]
Thanks Luca, it does appear to be fixed in master.  I appreciate you following up with me.

-Sean
