### ISSUE TITLE
libzmq not working inside a docker container

### ISSUE THREAD

**Issue by HarvaneetKaur** [zeromq/libzmq#4045]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
Not able to make zmq_connect call inside docker image

# Environment
ubuntu
* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

1.  Trying to make the connect call inside the docker using localhost at port:5555

# What's the actual result? (include assertion message & call stack if applicable)

Segementation fault

Thread 1 "unit_tests" received signal SIGSEGV, Segmentation fault.
0x00007ff6a68cb8de in zmq::ypipe_t<zmq::command_t, 16>::write(zmq::command_t const&, bool) () from /root/source/build/dist/lib/libzmq.so.5
(gdb) bt
#0  0x00007ff6a68cb8de in zmq::ypipe_t<zmq::command_t, 16>::write(zmq::command_t const&, bool) () from /root/source/build/dist/lib/libzmq.so.5
#1  0x00007ff6a68cb30c in zmq::mailbox_t::send(zmq::command_t const&) () from /root/source/build/dist/lib/libzmq.so.5
#2  0x00007ff6a68d0f1f in zmq::object_t::send_plug(zmq::own_t*, bool) () from /root/source/build/dist/lib/libzmq.so.5
#3  0x00007ff6a68d3fef in zmq::own_t::launch_child(zmq::own_t*) () from /root/source/build/dist/lib/libzmq.so.5
#4  0x00007ff6a68e737f in zmq::socket_base_t::add_endpoint(zmq::endpoint_uri_pair_t const&, zmq::own_t*, zmq::pipe_t*) ()
   from /root/source/build/dist/lib/libzmq.so.5
#5  0x00007ff6a68e7f28 in zmq::socket_base_t::connect_internal(char const*) () from /root/source/build/dist/lib/libzmq.so.5
#6  0x00007ff6a68e7232 in zmq::socket_base_t::connect(char const*) () from /root/source/build/dist/lib/libzmq.so.5
#7  0x00007ff6a6a951af in ZmqWrapper::ZmqWrapper(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /root/source/build/lib/libflexframelib.so

# What's the expected result?
Successfull connection

**Comment by bluca** [comment]
Is your wrapper referencing the socket from multiple threads?

**Comment by HarvaneetKaur** [comment]
> Is your wrapper referencing the socket from multiple threads?

No , Its just a single thread that I am using here .
