### ISSUE TITLE
GLIBC_2.28 not found when using Python after "pip install zmq" on Raspberry Pi 3b 

### ISSUE THREAD

**Issue by dangu** [zeromq/libzmq#4362]
# Issue description
Error when trying to use the python version of zmq on a Raspberry Pi with Raspbian OS.
The error is "version `GLIBC_2.28' not found"

# Environment
* Raspberry Pi 3b
* libzmq version (commit hash if unreleased): Using pip install, this is what I get: "Collecting zmq
  Downloading https://www.piwheels.org/simple/zmq/zmq-0.0.0-py3-none-any.whl (2.0 kB)
Collecting pyzmq
  Downloading https://www.piwheels.org/simple/pyzmq/pyzmq-22.3.0-cp39-cp39-linux_armv7l.whl (6.8 MB)"

* OS: Raspbian GNU/Linux 9 (stretch)
* Using Python 3.9.10 (I installed it with pyenv)

# Minimal test code / Steps to reproduce the issue

1. mkdir zmq_test && cd zmq_test
2. pip install zmq
3. python
4. Inside the python interpreter:
5. import zmq

# What's the actual result? (include assertion message & call stack if applicable)
    pi@raspberrypi:~/zmq_test $ python
    Python 3.9.10 (main, Jan 26 2022, 13:24:57) 
    [GCC 6.3.0 20170516] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import zmq
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'zmq'
    >>> 
    pi@raspberrypi:~/zmq_test $ pip install zmq
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Collecting zmq
      Downloading https://www.piwheels.org/simple/zmq/zmq-0.0.0-py3-none-any.whl (2.0 kB)
    Collecting pyzmq
      Downloading https://www.piwheels.org/simple/pyzmq/pyzmq-22.3.0-cp39-cp39-linux_armv7l.whl (6.8 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 3.4 MB/s eta 0:00:00
    Installing collected packages: pyzmq, zmq
    Successfully installed pyzmq-22.3.0 zmq-0.0.0
    pi@raspberrypi:~/Lokalt/zmq_test $ python
    Python 3.9.10 (main, Jan 26 2022, 13:24:57) 
    [GCC 6.3.0 20170516] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import zmq
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/pi/.pyenv/versions/3.9.10/lib/python3.9/site-packages/zmq/__init__.py", line 61, in <module>
        _load_libzmq()
      File "/home/pi/.pyenv/versions/3.9.10/lib/python3.9/site-packages/zmq/__init__.py", line 36, in _load_libzmq
        from . import libzmq
    ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /home/pi/.pyenv/versions/3.9.10/lib/python3.9/site-packages/zmq/libzmq.cpython-39-arm-linux-gnueabihf.so)
    >>> 

# What's the expected result?
The "import zmq" statement should succeed without errors

**Comment by dangu** [comment]
Progress: Following the instructions in "Building and installation" here:https://github.com/zeromq/pyzmq
Executing the following commands:
1. pip uninstall pyzmq

       [...] Successfully uninstalled pyzmq-22.3.0


2. sudo apt-get install libzmq3-dev

       Successfully installed pyzmq-22.3.0

3. python

       Python 3.7.12 (default, Jan 26 2022, 13:39:12) 
(Oops, apparently I was using 3.7.12 here, 3.9.10 above...)

4. import zmq

       >>> 

Wow! Works!

5. pip list

       Package    Version
       ---------- -------
       pip        22.0.4
       pyzmq      22.3.0
       setuptools 47.1.0

So, building with pip install --no-binary works.
