### ISSUE TITLE
Draft: dish.join problem

### ISSUE THREAD

**Issue by ShacharZi** [zeromq/libzmq#4428]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
When I running the dish-radio from draft , all attribute are working(bind, connect, recv) except join option.

the following issue was appear:

Traceback (most recent call last):
  File "C:/Users/ShacharZ/Desktop/pythonProject2/main.py", line 11, in <module>
    dish.join('1')
  File "zmq\backend\cython\socket.pyx", line 722, in zmq.backend.cython.socket.Socket.join
  File "zmq\backend\cython\checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

Process finished with exit code 1

# Environment
python with pyzmq
* libzmq version (commit hash if unreleased): 
* OS: 

# Minimal test code / Steps to reproduce the issue

import time
import zmq

ctx = zmq.Context.instance()
radio = ctx.socket(zmq.RADIO)
dish = ctx.socket(zmq.DISH)
dish.rcvtimeo = 10

dish.bind('udp://*:64067')
dish.join('1')
radio.connect('udp://127.0.0.1:64067')

# What's the actual result? (include assertion message & call stack if applicable)

Traceback (most recent call last):
  File "C:/Users/ShacharZ/Desktop/pythonProject2/main.py", line 11, in <module>
    dish.join('1')
  File "zmq\backend\cython\socket.pyx", line 722, in zmq.backend.cython.socket.Socket.join
  File "zmq\backend\cython\checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

# What's the expected result?
transfer message from radio server to dish client

**Comment by ljluestc** [comment]
```

import time
import zmq

# Create a ZeroMQ context
ctx = zmq.Context.instance()

# Create RADIO socket (Publisher)
radio = ctx.socket(zmq.RADIO)

# Create DISH socket (Subscriber)
dish = ctx.socket(zmq.DISH)

# Set a receive timeout for the DISH socket (10 seconds)
dish.rcvtimeo = 10000  # 10 seconds timeout

# Bind the DISH socket to a UDP port
dish.bind('udp://*:64067')

# Wait a bit to ensure binding is fully done before joining
time.sleep(1)  # Sleep for 1 second to give enough time for the binding to complete

# Join the multicast group '1'
try:
    dish.join('1')
    print("Joined the multicast group '1'.")
except zmq.error.Again as e:
    print(f"Error: {e}. Could not join the multicast group.")
    radio.close()
    dish.close()
    ctx.term()
    exit(1)

# Connect the RADIO socket to the same UDP address
radio.connect('udp://127.0.0.1:64067')

# Send a message using the RADIO socket
radio.send(b"Hello, world!")

# Receive the message using the DISH socket
try:
    message = dish.recv()
    print(f"Received message: {message.decode('utf-8')}")
except zmq.error.Again as e:
    print(f"Failed to receive message: {e}")

# Close the sockets and terminate the context
dish.close()
radio.close()
ctx.term()
```
