### ISSUE TITLE
Program terminated with signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by fvckcaib** [zeromq/libzmq#4636]
#0  0x00007fe708bb26d3 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00000000006f3031 in zmq::encoder_base_t<zmq::v2_encoder_t>::encode (this=0x7fe70005cd00, data_=0x7fe70804b168, size_=<optimized out>) at encoder.hpp:76
#2  0x00000000006eef43 in zmq::stream_engine_t::out_event (this=0x7fe700074750) at stream_engine.cpp:263
#3  0x00000000006ed74b in std::set<zmq::pipe_t*, std::less<zmq::pipe_t*>, std::allocator<zmq::pipe_t*> >::count (__x=@0x7fe70804b198: 0x15b2640, this=0x7fe70004ab54)
    at /usr/include/c++/8/bits/stl_tree.h:995
#4  zmq::session_base_t::write_activated (this=0x15959a0, pipe_=0x1) at session_base.cpp:255
#5  0x00000000006d4524 in zmq::io_thread_t::io_thread_t (this=0x0, ctx_=<optimized out>, tid_=<optimized out>) at io_thread.cpp:30
#6  0x00000000015f32b0 in ?? ()
#7  0x0000000001595fc0 in ?? ()
#8  0x00000000006d40e6 in zmq::epoll_t::rm_fd (this=0x7fe600000005, handle_=0x1) at epoll.cpp:77
#9  0x00007fe700074730 in ?? ()
#10 0x0000000000000000 in ?? ()

**Comment by ljluestc** [comment]
```

#include <zmq.hpp>
#include <iostream>

int main() {
    zmq::context_t context;

    // Create a publisher socket
    zmq::socket_t socket(context, zmq::socket_type::pub);
    socket.bind("tcp://*:5555");

    // Send a message
    try {
        zmq::message_t message(5);
        memcpy(message.data(), "Hello", 5);
        socket.send(message, zmq::send_flags::none);
    } catch (const zmq::error_t& e) {
        std::cerr << "Error sending message: " << e.what() << std::endl;
        socket.close();
        context.close();
        return 1;
    }

    // Close the socket and terminate context properly
    socket.close();
    context.close();

    return 0;
}
```
