### ISSUE TITLE
The program ocassionly crash in zmq, when program exits

### ISSUE THREAD

**Issue by leeshineSZ** [zeromq/libzmq#4760]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue description
The program ocassionly crash in zmq, when programe exits. It only appears when the program exits, when the promgram running, the zmq work no problem.

#0  0x0000007fb2d62ee4 in raise () from /lib/libc.so.6
No symbol table info available.
#1  0x0000007fb2d4fa78 in abort () from /lib/libc.so.6
No symbol table info available.
#2  0x0000007fb34457ec in zmq::zmq_abort(char const*) () from /usr/lib/libzmq.so.5
No symbol table info available.
#3  0x0000007fb3445084 in zmq::epoll_t::add_fd(int, zmq::i_poll_events*) () from /usr/lib/libzmq.so.5
No symbol table info available.
#4  0x0000007fb346f20c in zmq::tcp_connecter_t::start_connecting() () from /usr/lib/libzmq.so.5
No symbol table info available.
#5  0x0000007fb3457f38 in zmq::poller_base_t::execute_timers() () from /usr/lib/libzmq.so.5
No symbol table info available.
#6  0x0000007fb3444ba8 in zmq::epoll_t::loop() () from /usr/lib/libzmq.so.5
No symbol table info available.
#7  0x0000007fb3470208 in ?? () from /usr/lib/libzmq.so.5
No symbol table info available.
#8  0x0000007fb34efa44 in ?? () from /lib/libpthread.so.0
No symbol table info available.
#9  0x0000007fb2dfdddc in ?? () from /lib/libc.so.6

# Environment
arm
* libzmq version (commit hash if unreleased): 
5.2.4
* OS: 
linux
# Minimal test code / Steps to reproduce the issue

1.  

# What's the actual result? (include assertion message & call stack if applicable)

#0  0x0000007fb2d62ee4 in raise () from /lib/libc.so.6
No symbol table info available.
#1  0x0000007fb2d4fa78 in abort () from /lib/libc.so.6
No symbol table info available.
#2  0x0000007fb34457ec in zmq::zmq_abort(char const*) () from /usr/lib/libzmq.so.5
No symbol table info available.
#3  0x0000007fb3445084 in zmq::epoll_t::add_fd(int, zmq::i_poll_events*) () from /usr/lib/libzmq.so.5
No symbol table info available.
#4  0x0000007fb346f20c in zmq::tcp_connecter_t::start_connecting() () from /usr/lib/libzmq.so.5
No symbol table info available.
#5  0x0000007fb3457f38 in zmq::poller_base_t::execute_timers() () from /usr/lib/libzmq.so.5
No symbol table info available.
#6  0x0000007fb3444ba8 in zmq::epoll_t::loop() () from /usr/lib/libzmq.so.5
No symbol table info available.
#7  0x0000007fb3470208 in ?? () from /usr/lib/libzmq.so.5
No symbol table info available.
#8  0x0000007fb34efa44 in ?? () from /lib/libpthread.so.0
No symbol table info available.
#9  0x0000007fb2dfdddc in ?? () from /lib/libc.so.6

# What's the expected result?
Can I resolve the crash?

**Comment by keith-dev** [comment]
Have you provided a minimal program that reproduces the crash?

What platform have you reproduced the crash on?

**Comment by leeshineSZ** [comment]
when program exits, some thread block. After resolving the block, it no longer occurs.
